
title: 현대수학의 융합적 이해
description: "현대수학의 융합적 이해 학습 자료"
theme: just-the-docs
color_scheme: light

url: "https://cgsmath.github.io/pme/pme1/wiki"
baseurl: "/pme/pme1/wiki"

aux_links:
  GitHub Repository: https://github.com/cgsmath/pme
